/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * OfficeMainMenu.java
 *
 * Created on 09.okt.2011, 21:45:52
 */
package OfficeGUI;

import java.awt.Frame;

/**
 *
 * @author Henning
 */
public class OfficeMainMenu extends javax.swing.JPanel {

    /** Creates new form OfficeMainMenu */
    public OfficeMainMenu() {
        initComponents();
    }

   
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logOutButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        tableMenuButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        foodMenuButton = new javax.swing.JButton();
        accountingButton = new javax.swing.JButton();

        logOutButton.setText("Log Out");

        jLabel1.setText("Main Menu For Office");

        tableMenuButton.setText("Table Menu");

        jButton1.setText("Staff Management");

        foodMenuButton.setText("Food Menu");

        accountingButton.setText("Accounting");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(294, Short.MAX_VALUE)
                .addComponent(logOutButton)
                .addGap(33, 33, 33))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tableMenuButton, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(267, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(foodMenuButton)
                .addContainerGap(303, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(accountingButton)
                .addContainerGap(303, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addComponent(tableMenuButton)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(foodMenuButton)
                .addGap(18, 18, 18)
                .addComponent(accountingButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(logOutButton)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accountingButton;
    private javax.swing.JButton foodMenuButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton logOutButton;
    private javax.swing.JButton tableMenuButton;
    // End of variables declaration//GEN-END:variables
}
